FROM amazoncorretto:17-alpine3.16
ARG JAR_FILE=build/libs/UserRatingAPI-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","-Xmx3072m", "-Dspring.profiles.active=local", "/app.jar"]